runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- node_modules/
- client/node_modules/
- client/src/
- client/webpack.config.js
- client/package.json
- client/package-lock.json
- client/README.md

handlers:
- url: /api/.*
  script: src.api.app
  secure: always
- url: /statics
  static_dir: statics
  secure: always
- url: /
  mime_type: text/html
  static_files: client/public/index.html
  secure: always
  upload: client/public/index.html
- url: /
  static_dir: client/public/
  secure: always

