runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /css
  static_dir: public/css/

- url: /js
  static_dir: public/js/

- url: /.*
  script: openid.app
  secure: always
